[project]
name = "maeves-ecosphere"
version = "0.1.0"
description = "A tile-based procedural ecosystem simulation, with an object component system."

authors = [
    {name = "MolassesLover"}
]

[project.scripts]
maeves-ecosphere = "mecosphere:cli.main"

[build-system]
requires = ["setuptools", "cython"]

[tool.setuptools]
ext-modules = [
  { name = "mecosphere", sources = [
    "src/mecosphere/application.py",
    "src/mecosphere/components.py",
    "src/mecosphere/simulation.py",
    "src/mecosphere/tilemap.py"
  ] }
]